# Generated by Django 4.2.29 on 2026-03-17 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 3, 17, 11, 26, 28, 847115),
                verbose_name="Опубликована",
            ),
        ),
    ]
