# Generated by Django 4.2.29 on 2026-03-17 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_blog_id_alter_blog_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 3, 17, 11, 27, 36, 237926),
                verbose_name="Опубликована",
            ),
        ),
    ]
