# Generated by Django 4.2.29 on 2026-03-17 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_blog_author_alter_blog_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 3, 17, 22, 12, 5, 368577),
                verbose_name="Опубликована",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(2026, 3, 17, 22, 12, 5, 368577),
                        verbose_name="Дата комментария",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.blog",
                        verbose_name="Статья комментария",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарии к статье блога",
                "verbose_name_plural": "Комментарии к статьям блога",
                "db_table": "Comment",
                "ordering": ["-date"],
            },
        ),
    ]
