# Generated by Django 4.2.29 on 2026-03-17 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_blog_posted_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.FileField(
                default="temp.jpg", upload_to="", verbose_name="Путь к картине"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 3, 18, 0, 5, 35, 972039),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2026, 3, 18, 0, 5, 35, 973113),
                verbose_name="Дата комментария",
            ),
        ),
    ]
